apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}
  namespace: customer-{{ .Values.global.customer.name }}
  labels:
    {{- include "motion.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: motion-http
      protocol: TCP
      name: motion-http
  selector:
    app: {{ .Values.global.customer.name }}-{{ .Values.product }}
